app/urls.py
from django.urls import path, include
from app import views
from .views import *

urlpatterns = [
    path('home', home, name="home"),
    path('login/', login, name="login"),
    path('emp', emp, name="emp"),  
    path('show', show),
    path('index', index),
    path('edit/<int:id>', edit),  
    path('update/<int:id>', update),  
    path('delete/<int:id>', destroy),
    path('new_post', new_post, name="new_post"),
    path('show_post', show_post, name="show_post"),
    path('edit_post/<int:id>', edit_post),
    path('update_post/<int:id>', update_post),
    path('destroy_post/<int:id>', destroy_post),
]

blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.


class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)

    class Meta:  
        db_table = "employee"


class Posts(models.Model):
    title = models.CharField(max_length=50)
    body = models.CharField(max_length=350)
    category = models.CharField(max_length=50)
    blog_id = models.CharField(max_length=50)

    class Meta:
        db_table = "posts"



app/forms.py
from django import forms  
from .models import Employee, Posts


class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"


class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['blog_id', 'title', 'body', 'category']
        # fields = "__all__"

app/views.py
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import EmployeeForm
from .models import Employee, Posts
from .forms import PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# def index(request):
#
def index(request):
    posts = Posts.objects.all()  # fetching all post objects from database
    p = Paginator(posts, 1)  # creating a paginator object
    # getting the desired page number from url
    page_number = 1
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    context = {'page_obj': page_obj}
    # sending the page object to index.html
    return render(request, 'index.html', context)


# def index(request):
#     post = Posts.objects.all()
#     page = request.GET.get('page', 1)
#
#     paginator = Paginator(post, 10)
#     try:
#         post = paginator.page(page)
#     except PageNotAnInteger:
#         post = paginator.page(1)
#     except EmptyPage:
#         post = paginator.page(paginator.num_pages)
#
#     return render(request, 'post_list.html', { 'post': post })


def home(request):
    return render(request, 'home.html')


def login(request):
    return render(request, 'login.html')


def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        print(form.is_valid())
        print("hello")

        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except Exception as e:
                print(e)
                pass
    else:
        form = EmployeeForm()
    return render(request, 'forms.html', {'form': form})


def show(request):
    employees = Employee.objects.all()
    return render(request, "show.html", {'employees': employees})


def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, 'edit.html', {'employee': employee})


def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'employee': employee})


def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")


def new_post(request):
    if request.method == "POST":
        print("ghej")
        form = PostForm(request.POST)
        print(form)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show_post')
            except Exception as e:
                print(e)
                pass
    else:
        form = PostForm()
    return render(request, 'new_post.html', {'form': form})


def show_post(request):
    posts = Posts.objects.all()
    p = Paginator(posts, 1)  # creating a paginator object
    # getting the desired page number from url
    page_number = 1
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
        print(page_obj)
    context = {'page_obj': page_obj}
    # sending the page object to index.html
    return render(request, 'index.html', {'posts': posts})
    # return render(request, "post_list.html", {'posts': posts}, context)


def edit_post(request, id):
    post = Posts.objects.get(id=id)
    return render(request, 'edit_post.html', {'post': post})


def update_post(request, id):
    print('enter')
    post = Posts.objects.get(id=id)
    print(post)
    form = PostForm(request.POST, instance=post)
    for field in form:
        print("Field Error:", field.name, field.errors)
    print(form.is_valid())
    if form.is_valid():
        form.save()
        return redirect("/show_post")
    print('render')
    return render(request, 'edit_post.html', {'post': post})


def destroy_post(request, id):
    post = Posts.objects.get(id=id)
    post.delete()
    return redirect("/show_post")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
      crossorigin="anonymous"
    />

    <title>Blog</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand text-white" href="#">Blog</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active text-white" aria-current="page" href="#"
              >Home</a
            >
            <a class="nav-link text-white" href="{% url 'login' %}">Login</a>

            <li class="nav-item" active>
              <a
                class="nav-link active text-white"
                aria-current="page"
                href="{% url 'emp' %}"
                >Register</a
              >
            </li>

            <li class="nav-item">
              <a class="btn btn-info" aria-current="page" href="{% url 'new_post' %}"
                >Create New Blog</a>
            </li>
          </div>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <footer class="bg-dark p-3">
      <p class="text-center text-white">All rights</p>
    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{employee.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

app/templates/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<h1>{{post.id}}</h1>
<form method="POST" class="post-form" action="/update_post/{{post.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details {{post.id}}</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Blog Id:</label>
    <div class="col-sm-4">
        <input type="text" name="blog_id" id="id_bid" required maxlength="20" value="{{ post.blog_id }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Blog Name:</label>
    <div class="col-sm-4">
        <input type="text" name="title" id="id_title" required maxlength="100" value="{{ post.title }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Blog Body:</label>
    <div class="col-sm-4">
        <input type="text" name="body" id="id_body" required maxlength="254" value="{{ post.body }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Blog Category:</label>
    <div class="col-sm-4">
        <input type="text" name="category" id="id_category" required maxlength="15" value="{{ post.category }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

app/templates/forms.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
      {{ form.eid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.eemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

app/templates/home.html
{% extends "base.html"%} {% block content %}

<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-lg-4">
      <div class="card" style="width: 18rem">
        <img
          src="https://neilpatel.com/wp-content/uploads/2018/10/blog.jpg"
          class="card-img-top"
          alt="..."
        />
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
          <a href="#" class="btn btn-primary btn-sm" style="">Read More</a>
          <a href="{% url 'new_post' %}" class="btn btn-warning btn-sm">Edit</a>
          <a href="{% url 'show_post' %}" class="btn btn-danger btn-sm">Delete</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card" style="width: 18rem">
        <img
          src="https://neilpatel.com/wp-content/uploads/2018/10/blog.jpg"
          class="card-img-top"
          alt="..."
        />
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
          <a href="#" class="btn btn-primary btn-sm" style="">Read More</a>
          <a href="#" class="btn btn-warning btn-sm">Edit</a>
          <a href="#" class="btn btn-danger btn-sm">Delete</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card" style="width: 18rem">
        <img
          src="https://neilpatel.com/wp-content/uploads/2018/10/blog.jpg"
          class="card-img-top"
          alt="..."
        />
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
          <a href="#" class="btn btn-primary btn-sm" style="">Read More</a>
          <a href="#" class="btn btn-warning btn-sm">Edit</a>
          <a href="#" class="btn btn-danger btn-sm">Delete</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
        {% for post in page_obj.object_list %}
          {# note that the list of posts are in the page_obj.object_list not page_obj #}
            <small>{{post.blog_id}}</small>
            <h1>{{post.title}}</h1>
            <p>{{post.body}}</p>
         {% endfor %}
    </div>
    <center>
        {%if page_obj.has_previous %}
        {# whether the previous page exists #}
            <a href="?page={{page_obj.previous_page_number}}"><</a> {# link to the prev page #}
        {% endif %}
        <span>{{page_obj.number}}</span> {# the current page number #}

        {%if page_obj.has_next %}
        {# whether the next page exists #}
            <a href="?page={{page_obj.next_page_number}}">></a> {# link to the next page #}
        {% endif %}
    </center>

    <div class="page-links">
        {% if page.has_previous %}
        <a href="#">Previous Page</a>
        {% endif %}
        {% if page.has_next %}
        <a href="#">Next Page</a>
        {% endif %}
    </div>
</body>
</html>

app/templates/login.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
    </div>
    <div class="col-lg-6"></div>
  </div>
</div>

{% endblock %}

app/templates/new_post.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/new_post">
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>
 <div class="form-group row">
    <label class="col-sm-2 col-form-label">Blog Id:</label>
    <div class="col-sm-4">
      {{ form.blog_id }}
    </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Blog Title:</label>
    <div class="col-sm-4">  
      {{ form.title }}
    </div>
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Blog Body</label>
    <div class="col-sm-4">  
      {{ form.body }}
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Blog Category:</label>
    <div class="col-sm-4">  
      {{ form.category }}
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

app/templates/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post List</title>
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

</head>
<body>
<table class="table table-bordered">
    <thead>
    <tr>
        <th>Blog ID</th>
        <th>Blog Title</th>
        <th>Blog Body</th>
        <th>Blog Category</th>
    </tr>
    </thead>
    <tbody>
</table>
    <div class="container">
        {% for post in page_obj.object_list %}
          {# note that the list of posts are in the page_obj.object_list not page_obj #}
            <h1>{{post.title}}</h1>
            <small>{{post.id}}</small>
            <p>{{post.body}}</p>
            <hr/>
         {% endfor %}
    </div>
{% for post in posts %}
    <tr>
        <td>{{ post.blog_id }}</td>
        <td>{{ post.title }}</td>
        <td>{{ post.category }}</td>
        <td>{{ post.body }}</td>
        <td>
            <a href="/edit_post/{{ post.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/destroy_post/{{ post.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
<center>
        {%if page_obj.has_previous %} {# whether the previous page exists #}
            <a href="?page={{page_obj.previous_page_number}}"><</a> {# link to the prev page #}
        {% endif %}
        <span>{{page_obj.number}}</span> {# the current page number #}

        {%if page_obj.has_next %} {# whether the next page exists #}
            <a href="?page={{page_obj.next_page_number}}">></a> {# link to the next page #}
        {% endif %}
    </center>
<br>
<br>
<center><a href="/new_post" class="btn btn-primary">Add New Record</a></center>

</body>
</html>

app/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  